'use client';

import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// Metadata must be in a separate file or generated by a server component
// This is a client component, so we can't define metadata here

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAuthPage = ['/login', '/signup'].includes(pathname);
  const isDashboardPage = pathname === '/dashboard' || pathname?.startsWith('/dashboard/');

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased ${
          isDashboardPage ? '' : 'bg-gray-900 text-white'
        } min-h-screen flex flex-col`}
      >
        <Navbar />
        <main className={`${isAuthPage ? '' : 'pt-16'} flex-grow`}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
